name: Deploy Task Manager

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install and Build Frontend
      run: |
        cd frontend
        npm install
        npm run build
    
    - name: Deploy Frontend to S3
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1
    
    - name: Upload Frontend to S3
      run: |
        aws s3 sync frontend/build/ s3://task-manager-frontend-prakshal --delete
        echo "Frontend deployed successfully!"
    
    - name: Deploy Backend to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/www/task-manager
          echo "Pulling latest code..."
          git pull origin main
          echo "Installing dependencies..."
          cd backend
          npm install --production
          echo "Restarting application..."
          pm2 restart task-manager-backend || pm2 start ecosystem.config.js
          echo "Backend deployed successfully!"